local M = {}

function M.get(p)
  local hl = {}

  local function h(group, opts)
    hl[group] = opts
  end

  -- ===== BASE VIM GROUPS =====

  h("Normal",          { fg = p.fg,  bg = p.bg })
  h("NormalNC",        { fg = p.fg,  bg = p.bg1 })
  h("NormalFloat",     { fg = p.fg,  bg = p.bg0 })
  h("FloatBorder",     { fg = p.bg3, bg = p.bg0 })
  h("FloatTitle",      { fg = p.fg,  bg = p.bg0, bold = true })
  h("FloatFooter",     { fg = p.fg1, bg = p.bg0 })

  h("Comment",         { fg = p.fg2, italic = true })

  h("Constant",        { fg = p.yellow })
  h("String",          { fg = p.green })
  h("Character",       { fg = p.green })
  h("Number",          { fg = p.yellow })
  h("Boolean",         { fg = p.yellow, italic = true })
  h("Float",           { fg = p.yellow })

  h("Identifier",      { fg = p.fg })
  h("Function",        { fg = p.accent })

  h("Statement",       { fg = p.accent2 })
  h("Conditional",     { fg = p.accent })
  h("Repeat",          { fg = p.accent })
  h("Label",           { fg = p.blue })
  h("Operator",        { fg = p.fg1 })
  h("Keyword",         { fg = p.accent2 })
  h("Exception",       { fg = p.red })

  h("PreProc",         { fg = p.yellow })
  h("Include",         { fg = p.fg1, italic = true })
  h("Define",          { fg = p.yellow })
  h("Macro",           { fg = p.accent2 })
  h("PreCondit",       { fg = p.yellow })

  h("Type",            { fg = p.blue })
  h("StorageClass",    { fg = p.accent2 })
  h("Structure",       { fg = p.blue })
  h("Typedef",         { fg = p.blue })

  h("Special",         { fg = p.accent2 })
  h("SpecialChar",     { fg = p.accent2 })
  h("Tag",             { fg = p.blue })
  h("Delimiter",       { fg = p.fg2 })
  h("SpecialComment",  { fg = p.fg2, italic = true })
  h("Debug",           { fg = p.red })

  h("Underlined",      { underline = true })
  h("Ignore",          { fg = p.bg2 })
  h("Error",           { fg = p.red })
  h("Todo",            { fg = p.accent, bold = true })

  -- UI elements

  h("ColorColumn",     { bg = p.bg2 })
  h("Conceal",         { fg = p.fg3 })
  h("Cursor",          { fg = p.bg, bg = p.accent })
  h("CursorIM",        { fg = p.bg, bg = p.accent })
  h("lCursor",         { fg = p.bg, bg = p.accent })
  h("CursorColumn",    { bg = p.bg2 })
  h("CursorLine",      { bg = p.active_line })
  h("CursorLineFold",  { fg = p.fg2 })
  h("CursorLineSign",  { bg = p.bg })

  h("Directory",       { fg = p.blue })

  h("DiffAdd",         { bg = p.diff_add })
  h("DiffChange",      { bg = p.diff_change })
  h("DiffDelete",      { fg = p.git_delete, bg = p.diff_delete })
  h("DiffText",        { bg = p.diff_change, bold = true })

  h("EndOfBuffer",     { fg = p.bg2 })
  h("ErrorMsg",        { fg = p.red })

  h("VertSplit",       { fg = p.bg3 })
  h("WinSeparator",    { fg = p.bg3 })
  h("WinBar",          { fg = p.fg1, bg = p.bg })
  h("WinBarNC",        { fg = p.fg2, bg = p.bg1 })

  h("Folded",          { fg = p.fg2, bg = p.bg0 })
  h("FoldColumn",      { fg = p.fg2, bg = p.bg0 })

  h("SignColumn",      { fg = p.fg2, bg = p.bg })
  h("SignColumnSB",    { fg = p.fg2, bg = p.bg0 })

  h("IncSearch",       { fg = p.bg, bg = p.accent })
  h("Substitute",      { fg = p.bg, bg = p.yellow })
  h("Search",          { fg = p.bg, bg = p.accent2 })
  h("CurSearch",       { link = "IncSearch" })

  h("LineNr",          { fg = p.fg3 })
  h("LineNrAbove",     { fg = p.fg3 })
  h("LineNrBelow",     { fg = p.fg3 })
  h("CursorLineNr",    { fg = p.accent, bold = true })

  h("MatchParen",      { fg = p.accent, bg = p.bracket_bg, bold = true })

  h("ModeMsg",         { fg = p.fg, bold = true })
  h("MsgArea",         { fg = p.fg })
  h("MsgSeparator",    { fg = p.bg3 })
  h("MoreMsg",         { fg = p.green })
  h("NonText",         { fg = p.fg3 })

  h("Pmenu",           { fg = p.fg,  bg = p.bg0 })
  h("PmenuSel",        { fg = p.bg,  bg = p.accent })
  h("PmenuKind",       { fg = p.blue, bg = p.bg0 })
  h("PmenuKindSel",    { fg = p.bg,  bg = p.accent })
  h("PmenuExtra",      { fg = p.fg1, bg = p.bg0 })
  h("PmenuExtraSel",   { fg = p.bg,  bg = p.accent })
  h("PmenuSbar",       { bg = p.bg2 })
  h("PmenuThumb",      { bg = p.bg3 })

  h("Question",        { fg = p.green })
  h("QuickFixLine",    { bg = p.selection })

  h("SpecialKey",      { fg = p.fg3 })

  h("SpellBad",        { sp = p.red,    undercurl = true })
  h("SpellCap",        { sp = p.blue,   undercurl = true })
  h("SpellLocal",      { sp = p.green,  undercurl = true })
  h("SpellRare",       { sp = p.yellow, undercurl = true })

  h("StatusLine",      { fg = p.fg,  bg = p.bg_dark })
  h("StatusLineNC",    { fg = p.fg2, bg = p.bg_dark })

  h("TabLine",         { fg = p.fg2, bg = p.bg_dark })
  h("TabLineFill",     { bg = p.bg_dark })
  h("TabLineSel",      { fg = p.fg,  bg = p.bg })

  h("Title",           { fg = p.fg, bold = true })
  h("Visual",          { bg = p.selection })
  h("VisualNOS",       { bg = p.selection })
  h("WarningMsg",      { fg = p.yellow })
  h("Whitespace",      { fg = p.fg3 })
  h("WildMenu",        { fg = p.bg, bg = p.accent })

  -- ===== TREESITTER =====

  h("@variable",                    { fg = p.fg })
  h("@variable.builtin",            { fg = p.red })
  h("@variable.parameter",          { fg = p.fg })
  h("@variable.parameter.builtin",  { fg = p.red })
  h("@variable.member",             { fg = p.blue })

  h("@constant",                    { fg = p.yellow })
  h("@constant.builtin",            { fg = p.yellow })
  h("@constant.macro",              { fg = p.yellow })

  h("@module",                      { fg = p.fg1, italic = true })
  h("@module.builtin",              { fg = p.red, italic = true })
  h("@label",                       { fg = p.blue })

  h("@string",                      { fg = p.green })
  h("@string.regexp",               { fg = p.yellow })
  h("@string.escape",               { fg = p.accent2 })
  h("@string.special",              { fg = p.accent2 })
  h("@string.special.path",         { fg = p.blue, italic = true })
  h("@string.special.url",          { fg = p.blue, italic = true })
  h("@string.special.symbol",       { fg = p.accent2 })

  h("@character",                   { fg = p.green })
  h("@character.special",           { fg = p.accent2 })

  h("@boolean",                     { fg = p.yellow, italic = true })
  h("@number",                      { fg = p.yellow })
  h("@number.float",                { fg = p.yellow })

  h("@type",                        { fg = p.blue })
  h("@type.builtin",                { fg = p.blue, italic = true })
  h("@type.definition",             { fg = p.blue })

  h("@attribute",                   { fg = p.yellow })
  h("@attribute.builtin",           { fg = p.yellow })
  h("@property",                    { fg = p.fg1 })

  h("@function",                    { fg = p.accent })
  h("@function.builtin",            { fg = p.red })
  h("@function.call",               { fg = p.accent })
  h("@function.macro",              { fg = p.accent2 })
  h("@function.method",             { fg = p.accent })
  h("@function.method.call",        { fg = p.accent })

  h("@constructor",                 { fg = p.accent2 })
  h("@operator",                    { fg = p.fg1 })

  h("@keyword",                     { fg = p.accent2 })
  h("@keyword.modifier",            { fg = p.accent2 })
  h("@keyword.type",                { fg = p.accent2 })
  h("@keyword.function",            { fg = p.accent2 })
  h("@keyword.operator",            { fg = p.accent2 })
  h("@keyword.import",              { fg = p.fg1, italic = true })
  h("@keyword.export",              { fg = p.fg1, italic = true })
  h("@keyword.return",              { fg = p.accent })
  h("@keyword.repeat",              { fg = p.accent })
  h("@keyword.coroutine",           { fg = p.accent })
  h("@keyword.conditional",         { fg = p.accent })
  h("@keyword.conditional.ternary", { fg = p.accent })
  h("@keyword.exception",           { fg = p.red })
  h("@keyword.debug",               { fg = p.red })
  h("@keyword.directive",           { fg = p.yellow })
  h("@keyword.directive.define",    { fg = p.yellow })

  h("@punctuation.delimiter",       { fg = p.fg2 })
  h("@punctuation.bracket",         { fg = p.fg2 })
  h("@punctuation.special",         { fg = p.fg1 })

  h("@comment",                     { fg = p.fg2, italic = true })
  h("@comment.documentation",       { fg = p.fg1, italic = true })
  h("@comment.error",               { fg = p.red,     italic = true })
  h("@comment.warning",             { fg = p.yellow,  italic = true })
  h("@comment.hint",                { fg = p.blue,    italic = true })
  h("@comment.todo",                { fg = p.accent,  italic = true })
  h("@comment.note",                { fg = p.accent2, italic = true })

  h("@tag",                         { fg = p.blue })
  h("@tag.builtin",                 { fg = p.blue })
  h("@tag.attribute",               { fg = p.fg1, italic = true })
  h("@tag.delimiter",               { fg = p.fg2 })

  h("@diff.plus",                   { fg = p.git_add })
  h("@diff.minus",                  { fg = p.git_delete })
  h("@diff.delta",                  { fg = p.git_change })

  h("@markup.strong",               { bold = true })
  h("@markup.italic",               { italic = true })
  h("@markup.strikethrough",        { strikethrough = true })
  h("@markup.underline",            { underline = true })
  h("@markup.heading",              { fg = p.fg,      bold = true })
  h("@markup.heading.1",            { fg = p.accent,  bold = true })
  h("@markup.heading.2",            { fg = p.blue,    bold = true })
  h("@markup.heading.3",            { fg = p.green,   bold = true })
  h("@markup.heading.4",            { fg = p.yellow,  bold = true })
  h("@markup.heading.5",            { fg = p.red,     bold = true })
  h("@markup.heading.6",            { fg = p.fg1,     bold = true })
  h("@markup.link",                 { fg = p.accent })
  h("@markup.link.label",           { fg = p.accent })
  h("@markup.link.url",             { fg = p.blue, italic = true })
  h("@markup.raw",                  { fg = p.green })
  h("@markup.raw.block",            { fg = p.green })
  h("@markup.list",                 { fg = p.green })
  h("@markup.list.checked",         { fg = p.green })
  h("@markup.list.unchecked",       { fg = p.fg2 })

  -- ===== LSP SEMANTIC TOKENS =====

  h("@lsp.type.class",              { link = "@type" })
  h("@lsp.type.decorator",          { link = "@attribute" })
  h("@lsp.type.enum",               { link = "@type" })
  h("@lsp.type.enumMember",         { link = "@constant" })
  h("@lsp.type.function",           { link = "@function" })
  h("@lsp.type.interface",          { fg = p.blue, italic = true })
  h("@lsp.type.macro",              { link = "@function.macro" })
  h("@lsp.type.method",             { link = "@function.method" })
  h("@lsp.type.namespace",          { link = "@module" })
  h("@lsp.type.parameter",          { link = "@variable.parameter" })
  h("@lsp.type.property",           { link = "@property" })
  h("@lsp.type.struct",             { link = "@type" })
  h("@lsp.type.type",               { link = "@type" })
  h("@lsp.type.typeParameter",      { fg = p.blue, italic = true })
  h("@lsp.type.variable",           { link = "@variable" })
  h("@lsp.mod.deprecated",          { strikethrough = true })
  h("@lsp.mod.readonly",            { fg = p.yellow })

  -- ===== DIAGNOSTICS =====

  h("DiagnosticError",              { fg = p.red })
  h("DiagnosticWarn",               { fg = p.yellow })
  h("DiagnosticInfo",               { fg = p.blue })
  h("DiagnosticHint",               { fg = p.fg3 })
  h("DiagnosticOk",                 { fg = p.green })

  h("DiagnosticVirtualTextError",   { fg = p.red,    italic = true })
  h("DiagnosticVirtualTextWarn",    { fg = p.yellow, italic = true })
  h("DiagnosticVirtualTextInfo",    { fg = p.blue,   italic = true })
  h("DiagnosticVirtualTextHint",    { fg = p.fg3,    italic = true })

  h("DiagnosticUnderlineError",     { sp = p.red,    undercurl = true })
  h("DiagnosticUnderlineWarn",      { sp = p.yellow, undercurl = true })
  h("DiagnosticUnderlineInfo",      { sp = p.blue,   undercurl = true })
  h("DiagnosticUnderlineHint",      { sp = p.fg3,    undercurl = true })

  h("DiagnosticFloatingError",      { fg = p.red })
  h("DiagnosticFloatingWarn",       { fg = p.yellow })
  h("DiagnosticFloatingInfo",       { fg = p.blue })
  h("DiagnosticFloatingHint",       { fg = p.fg3 })

  h("DiagnosticSignError",          { fg = p.red })
  h("DiagnosticSignWarn",           { fg = p.yellow })
  h("DiagnosticSignInfo",           { fg = p.blue })
  h("DiagnosticSignHint",           { fg = p.fg3 })

  h("DiagnosticDeprecated",         { sp = p.fg3, strikethrough = true })
  h("DiagnosticUnnecessary",        { fg = p.fg3 })

  -- ===== LSP REFERENCES =====

  h("LspReferenceText",             { bg = p.read_bg })
  h("LspReferenceRead",             { bg = p.read_bg })
  h("LspReferenceWrite",            { bg = p.write_bg })
  h("LspSignatureActiveParameter",  { fg = p.accent, underline = true })
  h("LspInlayHint",                 { fg = p.fg3, italic = true })
  h("LspCodeLens",                  { fg = p.fg3 })
  h("LspCodeLensSeparator",         { fg = p.bg3 })

  -- ===== GITSIGNS =====

  h("GitSignsAdd",                  { fg = p.git_add })
  h("GitSignsChange",               { fg = p.git_change })
  h("GitSignsDelete",               { fg = p.git_delete })
  h("GitSignsTopdelete",            { fg = p.git_delete })
  h("GitSignsChangedelete",         { fg = p.git_change })
  h("GitSignsUntracked",            { fg = p.git_add })
  h("GitSignsAddNr",                { fg = p.git_add })
  h("GitSignsChangeNr",             { fg = p.git_change })
  h("GitSignsDeleteNr",             { fg = p.git_delete })
  h("GitSignsTopdeleteNr",          { fg = p.git_delete })
  h("GitSignsChangedeleteNr",       { fg = p.git_change })
  h("GitSignsAddLn",                { bg = p.diff_add })
  h("GitSignsChangeLn",             { bg = p.diff_change })
  h("GitSignsCurrentLineBlame",     { fg = p.fg3, italic = true })
  h("GitSignsAddInline",            { bg = p.diff_add })
  h("GitSignsChangeInline",         { bg = p.diff_change })
  h("GitSignsDeleteInline",         { bg = p.diff_delete })

  -- ===== TELESCOPE =====

  h("TelescopeBorder",              { fg = p.bg3,    bg = p.bg0 })
  h("TelescopeNormal",              { fg = p.fg,     bg = p.bg0 })
  h("TelescopePromptBorder",        { fg = p.accent, bg = p.bg2 })
  h("TelescopePromptNormal",        { fg = p.fg,     bg = p.bg2 })
  h("TelescopePromptPrefix",        { fg = p.accent, bg = p.bg2 })
  h("TelescopePromptCounter",       { fg = p.fg1,    bg = p.bg2 })
  h("TelescopePromptTitle",         { fg = p.bg,     bg = p.accent, bold = true })
  h("TelescopePreviewBorder",       { fg = p.bg3,    bg = p.bg0 })
  h("TelescopePreviewTitle",        { fg = p.bg,     bg = p.blue,   bold = true })
  h("TelescopePreviewNormal",       { fg = p.fg,     bg = p.bg0 })
  h("TelescopeResultsBorder",       { fg = p.bg3,    bg = p.bg0 })
  h("TelescopeResultsTitle",        { fg = p.fg1,    bg = p.bg0 })
  h("TelescopeResultsNormal",       { fg = p.fg,     bg = p.bg0 })
  h("TelescopeSelection",           { fg = p.fg,     bg = p.bg2 })
  h("TelescopeSelectionCaret",      { fg = p.accent, bg = p.bg2 })
  h("TelescopeMultiSelection",      { fg = p.accent2 })
  h("TelescopeMultiIcon",           { fg = p.accent2 })
  h("TelescopeMatching",            { fg = p.accent, bold = true })

  -- ===== INDENT-BLANKLINE =====

  -- ibl v3
  h("IblIndent",                    { fg = p.bg2 })
  h("IblScope",                     { fg = p.bg3 })
  h("IblWhitespace",                { fg = p.bg2 })
  -- ibl v2 (legacy)
  h("IndentBlanklineChar",               { fg = p.bg2 })
  h("IndentBlanklineContextChar",        { fg = p.bg3 })
  h("IndentBlanklineSpaceChar",          { fg = p.bg2 })
  h("IndentBlanklineSpaceCharBlankline", { fg = p.bg2 })

  -- ===== SNACKS.NVIM =====

  h("SnacksNormal",                         { fg = p.fg,  bg = p.bg0 })
  h("SnacksNormalNC",                       { fg = p.fg,  bg = p.bg0 })
  h("SnacksBackdrop",                       { bg = p.bg,  fg = p.fg3 })
  h("SnacksDashboardNormal",                { fg = p.fg,  bg = p.bg })
  h("SnacksDashboardDesc",                  { fg = p.fg1 })
  h("SnacksDashboardFile",                  { fg = p.accent })
  h("SnacksDashboardDir",                   { fg = p.fg2 })
  h("SnacksDashboardDate",                  { fg = p.fg3 })
  h("SnacksDashboardFooter",                { fg = p.fg3, italic = true })
  h("SnacksDashboardHeader",                { fg = p.accent, bold = true })
  h("SnacksDashboardIcon",                  { fg = p.accent })
  h("SnacksDashboardKey",                   { fg = p.accent2, bold = true })
  h("SnacksDashboardTitle",                 { fg = p.fg,  bold = true })
  h("SnacksDashboardSpecial",               { fg = p.fg2 })
  h("SnacksDashboardSectionTitle",          { fg = p.blue, bold = true })
  h("SnacksNotifierInfo",                   { fg = p.blue,   bg = p.bg0 })
  h("SnacksNotifierWarn",                   { fg = p.yellow, bg = p.bg0 })
  h("SnacksNotifierError",                  { fg = p.red,    bg = p.bg0 })
  h("SnacksNotifierDebug",                  { fg = p.fg1,    bg = p.bg0 })
  h("SnacksNotifierTrace",                  { fg = p.fg2,    bg = p.bg0 })
  h("SnacksNotifierBorderInfo",             { fg = p.blue })
  h("SnacksNotifierBorderWarn",             { fg = p.yellow })
  h("SnacksNotifierBorderError",            { fg = p.red })
  h("SnacksNotifierBorderDebug",            { fg = p.bg3 })
  h("SnacksNotifierBorderTrace",            { fg = p.bg3 })
  h("SnacksNotifierIconInfo",               { fg = p.blue })
  h("SnacksNotifierIconWarn",               { fg = p.yellow })
  h("SnacksNotifierIconError",              { fg = p.red })
  h("SnacksNotifierIconDebug",              { fg = p.fg1 })
  h("SnacksNotifierIconTrace",              { fg = p.fg2 })
  h("SnacksNotifierTitleInfo",              { fg = p.blue })
  h("SnacksNotifierTitleWarn",              { fg = p.yellow })
  h("SnacksNotifierTitleError",             { fg = p.red })
  h("SnacksNotifierTitleDebug",             { fg = p.fg1 })
  h("SnacksNotifierTitleTrace",             { fg = p.fg2 })
  h("SnacksIndent",                         { fg = p.bg2 })
  h("SnacksIndentScope",                    { fg = p.bg3 })
  h("SnacksPicker",                         { fg = p.fg,  bg = p.bg0 })
  h("SnacksPickerNormal",                   { fg = p.fg,  bg = p.bg0 })
  h("SnacksPickerBorder",                   { fg = p.bg3, bg = p.bg0 })
  h("SnacksPickerTitle",                    { fg = p.bg,  bg = p.accent, bold = true })
  h("SnacksPickerFooter",                   { fg = p.fg2, bg = p.bg0 })
  h("SnacksPickerSearch",                   { fg = p.fg,  bg = p.bg2 })
  h("SnacksPickerSelected",                 { fg = p.accent2 })
  h("SnacksPickerMatch",                    { fg = p.accent, bold = true })
  h("SnacksPickerCursorLine",               { bg = p.bg2 })
  h("SnacksPickerTotals",                   { fg = p.fg2, bg = p.bg0 })
  h("SnacksPickerInput",                    { fg = p.fg,     bg = p.bg2 })
  h("SnacksPickerInputBorder",              { fg = p.accent, bg = p.bg2 })
  h("SnacksPickerInputTitle",               { fg = p.bg,     bg = p.accent, bold = true })
  h("SnacksPickerList",                     { fg = p.fg,  bg = p.bg0 })
  h("SnacksPickerListBorder",               { fg = p.bg3, bg = p.bg0 })
  h("SnacksPickerListTitle",                { fg = p.fg1, bg = p.bg0 })
  h("SnacksPickerListCursorLine",           { bg = p.bg2 })
  h("SnacksPickerPreview",                  { fg = p.fg,  bg = p.bg0 })
  h("SnacksPickerPreviewBorder",            { fg = p.bg3, bg = p.bg0 })
  h("SnacksPickerPreviewTitle",             { fg = p.fg1, bg = p.bg0 })
  h("SnacksPickerPreviewCursorLine",        { bg = p.bg2 })
  h("SnacksPickerToggle",                   { fg = p.accent })
  h("SnacksPickerPrompt",                   { fg = p.accent, bg = p.bg2 })
  h("SnacksPickerPickWin",                  { fg = p.bg, bg = p.accent, bold = true })
  h("SnacksPickerPickWinCurrent",           { fg = p.bg, bg = p.accent2, bold = true })
  h("SnacksPickerDir",                      { fg = p.fg2 })
  h("SnacksPickerFile",                     { fg = p.fg })
  h("SnacksPickerPathHidden",               { fg = p.fg3 })
  h("SnacksPickerPathIgnored",              { fg = p.fg3 })
  h("SnacksPickerBufFlags",                 { fg = p.fg2 })
  h("SnacksPickerBufNr",                    { fg = p.fg3 })
  h("SnacksPickerKeymapLhs",                { fg = p.accent, bold = true })
  h("SnacksPickerKeymapRhs",                { fg = p.fg })
  h("SnacksPickerIcon",                     { fg = p.fg1 })
  h("SnacksPickerIconDirectory",            { fg = p.blue })
  h("SnacksPickerIconFile",                 { fg = p.fg1 })
  h("SnacksPickerLabel",                    { fg = p.accent })
  h("SnacksPickerComment",                  { fg = p.fg2 })
  h("SnacksPickerSpecial",                  { fg = p.accent2 })
  h("SnacksPickerRow",                      { fg = p.yellow })
  h("SnacksPickerCol",                      { fg = p.yellow })
  h("SnacksPickerDelim",                    { fg = p.fg2 })
  h("SnacksPickerTree",                     { fg = p.bg3 })
  h("SnacksPickerGitStatus",                { fg = p.fg2 })
  h("SnacksPickerGitStatusAdded",           { fg = p.git_add })
  h("SnacksPickerGitStatusModified",        { fg = p.git_change })
  h("SnacksPickerGitStatusDeleted",         { fg = p.git_delete })
  h("SnacksPickerGitStatusRenamed",         { fg = p.git_change })
  h("SnacksPickerGitStatusUntracked",       { fg = p.git_add })
  h("SnacksPickerGitStatusIgnored",         { fg = p.fg3 })
  h("SnacksPickerGitStatusStaged",          { fg = p.git_add })
  h("SnacksPickerGitStatusUnmerged",        { fg = p.red })
  h("SnacksPickerGitBranch",                { fg = p.accent })
  h("SnacksPickerGitCommit",                { fg = p.yellow })
  h("SnacksPickerGitDate",                  { fg = p.fg2 })
  h("SnacksPickerGitAuthor",                { fg = p.fg1 })
  h("SnacksPickerDiagnosticError",          { fg = p.red })
  h("SnacksPickerDiagnosticWarn",           { fg = p.yellow })
  h("SnacksPickerDiagnosticInfo",           { fg = p.blue })
  h("SnacksPickerDiagnosticHint",           { fg = p.fg3 })
  h("SnacksPickerDiagnosticSourceError",    { fg = p.red,    italic = true })
  h("SnacksPickerDiagnosticSourceWarn",     { fg = p.yellow, italic = true })
  h("SnacksPickerDiagnosticSourceInfo",     { fg = p.blue,   italic = true })
  h("SnacksPickerDiagnosticSourceHint",     { fg = p.fg3,    italic = true })
  h("SnacksPickerDiagnosticCode",           { fg = p.fg2 })
  h("SnacksPickerCode",                     { fg = p.fg })

  -- snacks.explorer (sidebar layout — uses the same SnacksPicker* groups above)
  h("SnacksExplorerFile",                   { fg = p.fg })
  h("SnacksExplorerDir",                    { fg = p.blue })
  h("SnacksExplorerDirOpen",                { fg = p.blue,  bold = true })
  h("SnacksExplorerSymlink",                { fg = p.blue,  italic = true })
  h("SnacksExplorerSpecial",                { fg = p.accent2 })
  h("SnacksExplorerExecutable",             { fg = p.green })
  h("SnacksExplorerSign",                   { fg = p.fg2 })
  h("SnacksExplorerSignGitStatus",          { fg = p.git_change })
  h("SnacksExplorerGitStatus",              { fg = p.fg2 })
  h("SnacksExplorerGitStatusAdded",         { fg = p.git_add })
  h("SnacksExplorerGitStatusModified",      { fg = p.git_change })
  h("SnacksExplorerGitStatusDeleted",       { fg = p.git_delete })
  h("SnacksExplorerGitStatusRenamed",       { fg = p.git_change })
  h("SnacksExplorerGitStatusUntracked",     { fg = p.git_add })
  h("SnacksExplorerGitStatusIgnored",       { fg = p.fg3 })
  h("SnacksExplorerGitStatusStaged",        { fg = p.git_add })
  h("SnacksExplorerGitStatusUnmerged",      { fg = p.red })
  h("SnacksInputNormal",                    { fg = p.fg,  bg = p.bg0 })
  h("SnacksInputBorder",                    { fg = p.accent, bg = p.bg0 })
  h("SnacksInputTitle",                     { fg = p.bg,  bg = p.accent })

  -- ===== MINI.NVIM =====

  h("MiniStatuslineModeNormal",             { fg = p.bg, bg = p.accent,  bold = true })
  h("MiniStatuslineModeInsert",             { fg = p.bg, bg = p.green,   bold = true })
  h("MiniStatuslineModeVisual",             { fg = p.bg, bg = p.yellow,  bold = true })
  h("MiniStatuslineModeReplace",            { fg = p.bg, bg = p.red,     bold = true })
  h("MiniStatuslineModeCommand",            { fg = p.bg, bg = p.blue,    bold = true })
  h("MiniStatuslineModeOther",              { fg = p.bg, bg = p.fg2,     bold = true })
  h("MiniStatuslineDevinfo",                { fg = p.fg1, bg = p.bg2 })
  h("MiniStatuslineFileinfo",               { fg = p.fg1, bg = p.bg2 })
  h("MiniStatuslineFilename",               { fg = p.fg,  bg = p.bg1 })
  h("MiniStatuslineInactive",               { fg = p.fg2, bg = p.bg_dark })
  h("MiniTablineCurrent",                   { fg = p.fg,  bg = p.bg,    bold = true })
  h("MiniTablineVisible",                   { fg = p.fg1, bg = p.bg1 })
  h("MiniTablineHidden",                    { fg = p.fg2, bg = p.bg_dark })
  h("MiniTablineModifiedCurrent",           { fg = p.accent,  bg = p.bg, bold = true })
  h("MiniTablineModifiedVisible",           { fg = p.accent2, bg = p.bg1 })
  h("MiniTablineModifiedHidden",            { fg = p.fg3, bg = p.bg_dark })
  h("MiniTablineFill",                      { bg = p.bg_dark })
  h("MiniTablineTabpagesection",            { fg = p.fg, bg = p.bg3 })
  h("MiniIndentscopeSymbol",                { fg = p.bg3 })
  h("MiniIndentscopePrefix",                { nocombine = true })
  h("MiniIconsAzure",                       { fg = p.blue })
  h("MiniIconsBlue",                        { fg = p.blue })
  h("MiniIconsCyan",                        { fg = p.green })
  h("MiniIconsGreen",                       { fg = p.green })
  h("MiniIconsGrey",                        { fg = p.fg2 })
  h("MiniIconsOrange",                      { fg = p.yellow })
  h("MiniIconsPurple",                      { fg = p.blue })
  h("MiniIconsRed",                         { fg = p.red })
  h("MiniIconsYellow",                      { fg = p.yellow })
  h("MiniClueBorder",                       { link = "FloatBorder" })
  h("MiniClueDescGroup",                    { fg = p.accent2, italic = true })
  h("MiniClueDescSingle",                   { link = "NormalFloat" })
  h("MiniClueNextKey",                      { fg = p.accent, bold = true })
  h("MiniClueNextKeyWithPostkeys",          { fg = p.red, bold = true })
  h("MiniClueSeparator",                    { fg = p.fg3 })
  h("MiniClueTitle",                        { fg = p.fg, bold = true })

  -- ===== WHICH-KEY.NVIM =====

  h("WhichKey",                             { fg = p.accent })
  h("WhichKeyBorder",                       { link = "FloatBorder" })
  h("WhichKeyDesc",                         { fg = p.fg })
  h("WhichKeyGroup",                        { fg = p.blue })
  h("WhichKeyIcon",                         { fg = p.accent })
  h("WhichKeyIconAzure",                    { fg = p.blue })
  h("WhichKeyIconBlue",                     { fg = p.blue })
  h("WhichKeyIconCyan",                     { fg = p.green })
  h("WhichKeyIconGreen",                    { fg = p.green })
  h("WhichKeyIconGrey",                     { fg = p.fg2 })
  h("WhichKeyIconOrange",                   { fg = p.yellow })
  h("WhichKeyIconPurple",                   { fg = p.blue })
  h("WhichKeyIconRed",                      { fg = p.red })
  h("WhichKeyIconYellow",                   { fg = p.yellow })
  h("WhichKeyNormal",                       { link = "NormalFloat" })
  h("WhichKeySeparator",                    { fg = p.fg3 })
  h("WhichKeyTitle",                        { fg = p.fg, bold = true })
  h("WhichKeyValue",                        { fg = p.fg1 })

  -- ===== FLASH.NVIM =====

  h("FlashBackdrop",                        { fg = p.fg3 })
  h("FlashCurrent",                         { fg = p.bg, bg = p.accent2, bold = true })
  h("FlashLabel",                           { fg = p.bg, bg = p.accent,  bold = true })
  h("FlashMatch",                           { fg = p.bg, bg = p.blue })
  h("FlashPrompt",                          { link = "MsgArea" })
  h("FlashPromptIcon",                      { fg = p.accent })

  -- ===== NOICE.NVIM =====

  h("NoiceCmdline",                         { fg = p.fg,  bg = p.bg0 })
  h("NoiceCmdlineIcon",                     { fg = p.accent })
  h("NoiceCmdlineIconSearch",               { fg = p.yellow })
  h("NoiceCmdlinePopup",                    { fg = p.fg,  bg = p.bg0 })
  h("NoiceCmdlinePopupBorder",              { fg = p.bg3, bg = p.bg0 })
  h("NoiceCmdlinePopupBorderSearch",        { fg = p.yellow, bg = p.bg0 })
  h("NoiceCmdlinePopupTitle",               { fg = p.fg1 })
  h("NoiceConfirm",                         { fg = p.fg,  bg = p.bg0 })
  h("NoiceConfirmBorder",                   { fg = p.accent, bg = p.bg0 })
  h("NoiceCursor",                          { link = "Cursor" })
  h("NoiceFormatConfirm",                   { fg = p.bg, bg = p.accent })
  h("NoiceFormatConfirmDefault",            { fg = p.bg, bg = p.blue })
  h("NoiceLspProgressClient",               { fg = p.accent, bold = true })
  h("NoiceLspProgressSpinner",              { fg = p.accent })
  h("NoiceLspProgressTitle",                { fg = p.fg1 })
  h("NoiceMini",                            { fg = p.fg, bg = p.bg_dark })
  h("NoicePopup",                           { fg = p.fg, bg = p.bg0 })
  h("NoicePopupBorder",                     { fg = p.bg3, bg = p.bg0 })
  h("NoicePopupmenu",                       { fg = p.fg, bg = p.bg0 })
  h("NoicePopupmenuBorder",                 { fg = p.bg3, bg = p.bg0 })
  h("NoicePopupmenuMatch",                  { fg = p.accent, bold = true })
  h("NoicePopupmenuSelected",               { fg = p.bg, bg = p.accent })
  h("NoiceScrollbar",                       { bg = p.bg2 })
  h("NoiceScrollbarThumb",                  { bg = p.bg3 })
  h("NoiceSplitBorder",                     { fg = p.bg3 })
  h("NoiceVirtualText",                     { fg = p.fg1 })

  -- ===== BLINK.CMP =====

  h("BlinkCmpMenu",                         { fg = p.fg,  bg = p.bg0 })
  h("BlinkCmpMenuBorder",                   { fg = p.bg3, bg = p.bg0 })
  h("BlinkCmpMenuSelection",                { fg = p.bg,  bg = p.accent })
  h("BlinkCmpScrollBarThumb",               { bg = p.bg3 })
  h("BlinkCmpScrollBarGutter",              { bg = p.bg2 })
  h("BlinkCmpLabel",                        { fg = p.fg })
  h("BlinkCmpLabelDeprecated",              { fg = p.fg3, strikethrough = true })
  h("BlinkCmpLabelMatch",                   { fg = p.accent, bold = true })
  h("BlinkCmpLabelDetail",                  { fg = p.fg1 })
  h("BlinkCmpLabelDescription",             { fg = p.fg2 })
  h("BlinkCmpKind",                         { fg = p.blue })
  h("BlinkCmpKindText",                     { fg = p.fg })
  h("BlinkCmpKindMethod",                   { fg = p.accent })
  h("BlinkCmpKindFunction",                 { fg = p.accent })
  h("BlinkCmpKindConstructor",              { fg = p.accent2 })
  h("BlinkCmpKindField",                    { fg = p.blue })
  h("BlinkCmpKindVariable",                 { fg = p.fg })
  h("BlinkCmpKindClass",                    { fg = p.blue })
  h("BlinkCmpKindInterface",                { fg = p.blue })
  h("BlinkCmpKindModule",                   { fg = p.fg1 })
  h("BlinkCmpKindProperty",                 { fg = p.fg1 })
  h("BlinkCmpKindUnit",                     { fg = p.yellow })
  h("BlinkCmpKindValue",                    { fg = p.yellow })
  h("BlinkCmpKindEnum",                     { fg = p.blue })
  h("BlinkCmpKindKeyword",                  { fg = p.accent2 })
  h("BlinkCmpKindSnippet",                  { fg = p.accent2 })
  h("BlinkCmpKindColor",                    { fg = p.green })
  h("BlinkCmpKindFile",                     { fg = p.fg1 })
  h("BlinkCmpKindReference",                { fg = p.fg1 })
  h("BlinkCmpKindFolder",                   { fg = p.fg1 })
  h("BlinkCmpKindEnumMember",               { fg = p.yellow })
  h("BlinkCmpKindConstant",                 { fg = p.yellow })
  h("BlinkCmpKindStruct",                   { fg = p.blue })
  h("BlinkCmpKindEvent",                    { fg = p.yellow })
  h("BlinkCmpKindOperator",                 { fg = p.fg1 })
  h("BlinkCmpKindTypeParameter",            { fg = p.blue })
  h("BlinkCmpDoc",                          { fg = p.fg,  bg = p.bg0 })
  h("BlinkCmpDocBorder",                    { fg = p.bg3, bg = p.bg0 })
  h("BlinkCmpDocCursorLine",                { bg = p.bg2 })
  h("BlinkCmpDocSeparator",                 { fg = p.bg3, bg = p.bg0 })
  h("BlinkCmpSource",                       { fg = p.fg3 })
  h("BlinkCmpGhostText",                    { fg = p.fg3, italic = true })
  h("BlinkCmpSignatureHelp",                { fg = p.fg,  bg = p.bg0 })
  h("BlinkCmpSignatureHelpBorder",          { fg = p.bg3, bg = p.bg0 })
  h("BlinkCmpSignatureHelpActiveParameter", { fg = p.accent, underline = true })

  -- ===== TROUBLE.NVIM =====

  h("TroubleNormal",                        { fg = p.fg, bg = p.bg0 })
  h("TroubleNormalNC",                      { fg = p.fg, bg = p.bg0 })
  h("TroubleBasename",                      { fg = p.fg, bold = true })
  h("TroubleCode",                          { fg = p.fg2 })
  h("TroubleCount",                         { fg = p.accent, bold = true })
  h("TroubleDirectory",                     { fg = p.blue })
  h("TroubleFilename",                      { fg = p.fg })
  h("TroubleIconFunction",                  { fg = p.accent })
  h("TroubleIconMethod",                    { fg = p.accent })
  h("TroubleIconClass",                     { fg = p.blue })
  h("TroubleIconConstant",                  { fg = p.yellow })
  h("TroubleIconFile",                      { fg = p.fg1 })
  h("TroubleIconDirectory",                 { fg = p.blue })
  h("TroubleIconString",                    { fg = p.green })
  h("TroubleIconVariable",                  { fg = p.fg })
  h("TroubleIconModule",                    { fg = p.fg1 })
  h("TroubleIndent",                        { fg = p.bg3 })
  h("TroublePos",                           { fg = p.fg3 })
  h("TroublePreview",                       { bg = p.selection })
  h("TroubleSource",                        { fg = p.fg2 })
  h("TroubleText",                          { fg = p.fg })

  -- ===== TODO-COMMENTS.NVIM =====

  h("TodoBgFIX",                            { fg = p.bg, bg = p.red,     bold = true })
  h("TodoBgHACK",                           { fg = p.bg, bg = p.yellow,  bold = true })
  h("TodoBgNOTE",                           { fg = p.bg, bg = p.blue,    bold = true })
  h("TodoBgPERF",                           { fg = p.bg, bg = p.accent2, bold = true })
  h("TodoBgTEST",                           { fg = p.bg, bg = p.blue,    bold = true })
  h("TodoBgTODO",                           { fg = p.bg, bg = p.accent,  bold = true })
  h("TodoBgWARN",                           { fg = p.bg, bg = p.yellow,  bold = true })
  h("TodoFgFIX",                            { fg = p.red })
  h("TodoFgHACK",                           { fg = p.yellow })
  h("TodoFgNOTE",                           { fg = p.blue })
  h("TodoFgPERF",                           { fg = p.accent2 })
  h("TodoFgTEST",                           { fg = p.blue })
  h("TodoFgTODO",                           { fg = p.accent })
  h("TodoFgWARN",                           { fg = p.yellow })
  h("TodoSignFIX",                          { link = "TodoFgFIX" })
  h("TodoSignHACK",                         { link = "TodoFgHACK" })
  h("TodoSignNOTE",                         { link = "TodoFgNOTE" })
  h("TodoSignPERF",                         { link = "TodoFgPERF" })
  h("TodoSignTEST",                         { link = "TodoFgTEST" })
  h("TodoSignTODO",                         { link = "TodoFgTODO" })
  h("TodoSignWARN",                         { link = "TodoFgWARN" })

  -- ===== NEO-TREE.NVIM =====

  h("NeoTreeNormal",                        { fg = p.fg,  bg = p.bg0 })
  h("NeoTreeNormalNC",                      { fg = p.fg,  bg = p.bg0 })
  h("NeoTreeDimText",                       { fg = p.fg3 })
  h("NeoTreeDirectoryIcon",                 { fg = p.blue })
  h("NeoTreeDirectoryName",                 { fg = p.fg })
  h("NeoTreeDotfile",                       { fg = p.fg2 })
  h("NeoTreeFileIcon",                      { fg = p.fg1 })
  h("NeoTreeFileName",                      { fg = p.fg })
  h("NeoTreeFileNameOpened",                { fg = p.accent })
  h("NeoTreeFilterTerm",                    { fg = p.accent, bold = true })
  h("NeoTreeFloatBorder",                   { link = "FloatBorder" })
  h("NeoTreeFloatTitle",                    { link = "FloatTitle" })
  h("NeoTreeGitAdded",                      { fg = p.git_add })
  h("NeoTreeGitConflict",                   { fg = p.red, bold = true })
  h("NeoTreeGitDeleted",                    { fg = p.git_delete })
  h("NeoTreeGitIgnored",                    { fg = p.fg3 })
  h("NeoTreeGitModified",                   { fg = p.git_change })
  h("NeoTreeGitRenamed",                    { fg = p.git_change })
  h("NeoTreeGitStaged",                     { fg = p.git_add })
  h("NeoTreeGitUnstaged",                   { fg = p.yellow })
  h("NeoTreeGitUntracked",                  { fg = p.git_add })
  h("NeoTreeIndentMarker",                  { fg = p.bg3 })
  h("NeoTreeModified",                      { fg = p.accent2 })
  h("NeoTreeRootName",                      { fg = p.accent, bold = true })
  h("NeoTreeSymbolicLinkTarget",            { fg = p.blue, italic = true })
  h("NeoTreeTabActive",                     { fg = p.fg,  bg = p.bg0, bold = true })
  h("NeoTreeTabInactive",                   { fg = p.fg2, bg = p.bg_dark })
  h("NeoTreeTabSeparatorActive",            { fg = p.accent, bg = p.bg0 })
  h("NeoTreeTabSeparatorInactive",          { fg = p.bg2,   bg = p.bg_dark })
  h("NeoTreeTitleBar",                      { fg = p.bg, bg = p.accent, bold = true })
  h("NeoTreeWinSeparator",                  { fg = p.bg3, bg = p.bg0 })

  -- ===== NVIM-TREE.LUA =====

  h("NvimTreeNormal",                       { fg = p.fg,  bg = p.bg0 })
  h("NvimTreeNormalNC",                     { fg = p.fg,  bg = p.bg0 })
  h("NvimTreeNormalFloat",                  { fg = p.fg,  bg = p.bg0 })
  h("NvimTreeEndOfBuffer",                  { fg = p.bg0, bg = p.bg0 })
  h("NvimTreeWinSeparator",                 { fg = p.bg3, bg = p.bg0 })
  h("NvimTreeRootFolder",                   { fg = p.accent, bold = true })
  h("NvimTreeFolderIcon",                   { fg = p.blue })
  h("NvimTreeFolderName",                   { fg = p.fg })
  h("NvimTreeOpenedFolderName",             { fg = p.blue, bold = true })
  h("NvimTreeEmptyFolderName",              { fg = p.fg2 })
  h("NvimTreeClosedFolderIcon",             { fg = p.blue })
  h("NvimTreeOpenedFolderIcon",             { fg = p.blue })
  h("NvimTreeFileIcon",                     { fg = p.fg1 })
  h("NvimTreeOpenedFile",                   { fg = p.accent })
  h("NvimTreeSpecialFile",                  { fg = p.accent2, underline = true })
  h("NvimTreeExecFile",                     { fg = p.green })
  h("NvimTreeSymlink",                      { fg = p.blue, italic = true })
  h("NvimTreeIndentMarker",                 { fg = p.bg3 })
  h("NvimTreeGitDirty",                     { fg = p.git_change })
  h("NvimTreeGitStaged",                    { fg = p.git_add })
  h("NvimTreeGitMerge",                     { fg = p.yellow })
  h("NvimTreeGitRenamed",                   { fg = p.git_change })
  h("NvimTreeGitNew",                       { fg = p.git_add })
  h("NvimTreeGitDeleted",                   { fg = p.git_delete })
  h("NvimTreeGitIgnored",                   { fg = p.fg3 })
  h("NvimTreeFileDirty",                    { fg = p.git_change })
  h("NvimTreeFileStaged",                   { fg = p.git_add })
  h("NvimTreeFileMerge",                    { fg = p.yellow })
  h("NvimTreeFileRenamed",                  { fg = p.git_change })
  h("NvimTreeFileNew",                      { fg = p.git_add })
  h("NvimTreeFileDeleted",                  { fg = p.git_delete })
  h("NvimTreeFileIgnored",                  { fg = p.fg3 })
  h("NvimTreeStatusLine",                   { fg = p.fg, bg = p.bg0 })
  h("NvimTreeStatusLineNC",                 { fg = p.fg2, bg = p.bg0 })
  h("NvimTreeCursorLine",                   { bg = p.bg2 })
  h("NvimTreeCursorColumn",                 { bg = p.bg2 })
  h("NvimTreeLiveFilterPrefix",             { fg = p.accent, bold = true })
  h("NvimTreeLiveFilterValue",              { fg = p.fg, bold = true })

  -- ===== BUFFERLINE.NVIM =====

  h("BufferLineFill",                       { bg = p.bg_dark })
  h("BufferLineBackground",                 { fg = p.fg2, bg = p.bg_dark })
  h("BufferLineBufferVisible",              { fg = p.fg1, bg = p.bg_dark })
  h("BufferLineBufferSelected",             { fg = p.fg,  bg = p.bg, bold = true })
  h("BufferLineTab",                        { fg = p.fg2, bg = p.bg_dark })
  h("BufferLineTabSelected",                { fg = p.fg,  bg = p.bg })
  h("BufferLineTabClose",                   { fg = p.red, bg = p.bg_dark })
  h("BufferLineCloseButton",                { fg = p.fg2, bg = p.bg_dark })
  h("BufferLineCloseButtonVisible",         { fg = p.fg1, bg = p.bg_dark })
  h("BufferLineCloseButtonSelected",        { fg = p.red, bg = p.bg })
  h("BufferLineSeparator",                  { fg = p.bg_dark, bg = p.bg_dark })
  h("BufferLineSeparatorVisible",           { fg = p.bg_dark, bg = p.bg_dark })
  h("BufferLineSeparatorSelected",          { fg = p.bg_dark, bg = p.bg })
  h("BufferLineIndicator",                  { fg = p.bg_dark, bg = p.bg_dark })
  h("BufferLineIndicatorSelected",          { fg = p.accent, bg = p.bg })
  h("BufferLineModified",                   { fg = p.accent2, bg = p.bg_dark })
  h("BufferLineModifiedVisible",            { fg = p.accent2, bg = p.bg_dark })
  h("BufferLineModifiedSelected",           { fg = p.accent2, bg = p.bg })
  h("BufferLineDuplicate",                  { fg = p.fg3, bg = p.bg_dark, italic = true })
  h("BufferLineDuplicateVisible",           { fg = p.fg2, bg = p.bg_dark, italic = true })
  h("BufferLineDuplicateSelected",          { fg = p.fg1, bg = p.bg, italic = true })
  h("BufferLineDiagnosticError",            { fg = p.red, bg = p.bg_dark })
  h("BufferLineDiagnosticWarn",             { fg = p.yellow, bg = p.bg_dark })
  h("BufferLineDiagnosticInfo",             { fg = p.blue, bg = p.bg_dark })
  h("BufferLineDiagnosticHint",             { fg = p.fg3, bg = p.bg_dark })

  -- ===== LUALINE.NVIM (fallback theme groups) =====

  h("lualine_a_normal",                     { fg = p.bg, bg = p.accent, bold = true })
  h("lualine_a_insert",                     { fg = p.bg, bg = p.green,  bold = true })
  h("lualine_a_visual",                     { fg = p.bg, bg = p.yellow, bold = true })
  h("lualine_a_replace",                    { fg = p.bg, bg = p.red,    bold = true })
  h("lualine_a_command",                    { fg = p.bg, bg = p.blue,   bold = true })
  h("lualine_a_terminal",                   { fg = p.bg, bg = p.accent2, bold = true })
  h("lualine_a_inactive",                   { fg = p.fg2, bg = p.bg_dark })
  h("lualine_b_normal",                     { fg = p.fg1, bg = p.bg2 })
  h("lualine_b_inactive",                   { fg = p.fg2, bg = p.bg_dark })
  h("lualine_c_normal",                     { fg = p.fg,  bg = p.bg_dark })
  h("lualine_c_inactive",                   { fg = p.fg2, bg = p.bg_dark })

  -- ===== NOTIFY.NVIM =====

  h("NotifyERRORBorder",                    { fg = p.red,    bg = p.bg0 })
  h("NotifyWARNBorder",                     { fg = p.yellow, bg = p.bg0 })
  h("NotifyINFOBorder",                     { fg = p.blue,   bg = p.bg0 })
  h("NotifyDEBUGBorder",                    { fg = p.fg1,    bg = p.bg0 })
  h("NotifyTRACEBorder",                    { fg = p.fg2,    bg = p.bg0 })
  h("NotifyERRORIcon",                      { fg = p.red })
  h("NotifyWARNIcon",                       { fg = p.yellow })
  h("NotifyINFOIcon",                       { fg = p.blue })
  h("NotifyDEBUGIcon",                      { fg = p.fg1 })
  h("NotifyTRACEIcon",                      { fg = p.fg2 })
  h("NotifyERRORTitle",                     { fg = p.red,    bold = true })
  h("NotifyWARNTitle",                      { fg = p.yellow, bold = true })
  h("NotifyINFOTitle",                      { fg = p.blue,   bold = true })
  h("NotifyDEBUGTitle",                     { fg = p.fg1,    bold = true })
  h("NotifyTRACETitle",                     { fg = p.fg2,    bold = true })
  h("NotifyERRORBody",                      { fg = p.fg, bg = p.bg0 })
  h("NotifyWARNBody",                       { fg = p.fg, bg = p.bg0 })
  h("NotifyINFOBody",                       { fg = p.fg, bg = p.bg0 })
  h("NotifyDEBUGBody",                      { fg = p.fg, bg = p.bg0 })
  h("NotifyTRACEBody",                      { fg = p.fg, bg = p.bg0 })

  -- ===== DRESSING.NVIM =====

  h("DressingInputBorder",                  { link = "FloatBorder" })
  h("DressingSelectBorder",                 { link = "FloatBorder" })

  -- ===== LAZY.NVIM =====

  h("LazyNormal",                           { fg = p.fg,  bg = p.bg0 })
  h("LazyButton",                           { fg = p.fg1, bg = p.bg2 })
  h("LazyButtonActive",                     { fg = p.bg,  bg = p.accent, bold = true })
  h("LazyH1",                               { fg = p.accent, bold = true })
  h("LazyH2",                               { fg = p.blue,   bold = true })
  h("LazySpecial",                          { fg = p.accent2 })
  h("LazyProp",                             { fg = p.fg1 })
  h("LazyValue",                            { fg = p.green })
  h("LazyDir",                              { fg = p.blue })
  h("LazyUrl",                              { fg = p.blue, italic = true })
  h("LazyCommit",                           { fg = p.yellow })
  h("LazyReasonCmd",                        { fg = p.accent })
  h("LazyReasonEvent",                      { fg = p.accent2 })
  h("LazyReasonFt",                         { fg = p.blue })
  h("LazyReasonKeys",                       { fg = p.green })
  h("LazyReasonPlugin",                     { fg = p.yellow })
  h("LazyReasonRuntime",                    { fg = p.red })
  h("LazyReasonSource",                     { fg = p.fg1 })
  h("LazyReasonStart",                      { fg = p.fg2 })
  h("LazyProgressDone",                     { fg = p.green, bold = true })
  h("LazyProgressTodo",                     { fg = p.fg3, bold = true })

  -- ===== MASON.NVIM =====

  h("MasonNormal",                          { fg = p.fg,  bg = p.bg0 })
  h("MasonHeader",                          { fg = p.bg,  bg = p.accent, bold = true })
  h("MasonHeaderSecondary",                 { fg = p.bg,  bg = p.blue,   bold = true })
  h("MasonHighlight",                       { fg = p.accent })
  h("MasonHighlightBlock",                  { fg = p.bg,  bg = p.accent })
  h("MasonHighlightBlockBold",              { fg = p.bg,  bg = p.accent, bold = true })
  h("MasonHighlightSecondary",              { fg = p.blue })
  h("MasonHighlightBlockSecondary",         { fg = p.bg,  bg = p.blue })
  h("MasonHighlightBlockBoldSecondary",     { fg = p.bg,  bg = p.blue, bold = true })
  h("MasonMuted",                           { fg = p.fg2 })
  h("MasonMutedBlock",                      { fg = p.fg2, bg = p.bg2 })
  h("MasonError",                           { fg = p.red })

  return hl
end

return M
